controller_names:
  - joint_trajectory_controller
  - forward_position_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

forward_position_controller:
  action_ns: forward_position_controller
  type: Float64MultiArray
  default: false
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
